apiVersion: datakit.infoblox.dev/v1alpha1
kind: DataSet
metadata:
  name: pg-namespaces
  labels:
    domain: k8s-report
    tier: reporting
spec:
  store: pg-warehouse
  table: reporting.k8s_namespaces
