apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-redpanda
  labels:
    app: redpanda
    app.kubernetes.io/name: redpanda
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: redpanda
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: redpanda
        app.kubernetes.io/name: redpanda
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: redpanda
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - rpk
            - redpanda
            - start
            - --mode
            - dev-container
            - --smp
            - "1"
            - --memory
            - 512M
            - --overprovisioned
            - --kafka-addr
            - 0.0.0.0:9092
            - --advertise-kafka-addr
            - localhost:9092
            - --schema-registry-addr
            - 0.0.0.0:8081
            - --pandaproxy-addr
            - 0.0.0.0:8082
          ports:
            - name: kafka
              containerPort: 9092
              protocol: TCP
            - name: schema-registry
              containerPort: 8081
              protocol: TCP
            - name: http-proxy
              containerPort: 8082
              protocol: TCP
            - name: admin
              containerPort: 9644
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: kafka
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: kafka
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
