apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redpanda
  labels:
    app: redpanda
    app.kubernetes.io/name: redpanda
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.kafka.port }}
      targetPort: kafka
      protocol: TCP
      name: kafka
    - port: {{ .Values.service.schemaRegistry.port }}
      targetPort: schema-registry
      protocol: TCP
      name: schema-registry
    - port: {{ .Values.service.httpProxy.port }}
      targetPort: http-proxy
      protocol: TCP
      name: http-proxy
    - port: {{ .Values.service.adminApi.port }}
      targetPort: admin
      protocol: TCP
      name: admin
  selector:
    app: redpanda
    app.kubernetes.io/instance: {{ .Release.Name }}
