# Makefile for {{.Name}}
#
# Project-specific targets go here. Common targets are provided by
# .datakit/Makefile.common which is managed by the dp CLI.
#
# Add your own targets below. Use ## comments for help text:
#   my-target: ## Description shown in make help

include .datakit/Makefile.common
