apiVersion: datakit.infoblox.dev/v1alpha1
kind: Store
metadata:
  name: pg-warehouse
spec:
  connector: postgres
  connection:
    connection_string: "postgresql://dkuser:dkpassword@dk-postgres-postgresql.dk-local.svc.cluster.local:5432/datakit?sslmode=disable"
