FROM golang:1.21-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o /source .

FROM alpine:3.19
COPY --from=builder /source /source
ENTRYPOINT ["/source"]
