apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-localstack
  labels:
    app: localstack
    app.kubernetes.io/name: localstack
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: localstack
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: localstack
        app.kubernetes.io/name: localstack
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: localstack
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SERVICES
              value: "{{ .Values.services }}"
            - name: DEBUG
              value: "0"
            - name: EAGER_SERVICE_LOADING
              value: "1"
          ports:
            - name: gateway
              containerPort: 4566
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /_localstack/health
              port: gateway
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /_localstack/health
              port: gateway
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
