apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-localstack
  labels:
    app: localstack
    app.kubernetes.io/name: localstack
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: gateway
      protocol: TCP
      name: gateway
  selector:
    app: localstack
    app.kubernetes.io/instance: {{ .Release.Name }}
