apiVersion: data.infoblox.com/v1alpha1
kind: Store
metadata:
  name: raw-bucket
  labels:
    environment: local
spec:
  connector: s3
  connection:
    bucket: dp-raw
    endpoint: http://localhost:4566
    region: us-east-1
    pathStyle: true
  secrets:
    accessKeyId: test
    secretAccessKey: test
---
apiVersion: data.infoblox.com/v1alpha1
kind: Store
metadata:
  name: staging-bucket
  labels:
    environment: local
spec:
  connector: s3
  connection:
    bucket: dp-staging
    endpoint: http://localhost:4566
    region: us-east-1
    pathStyle: true
  secrets:
    accessKeyId: test
    secretAccessKey: test
---
apiVersion: data.infoblox.com/v1alpha1
kind: Store
metadata:
  name: curated-bucket
  labels:
    environment: local
spec:
  connector: s3
  connection:
    bucket: dp-curated
    endpoint: http://localhost:4566
    region: us-east-1
    pathStyle: true
  secrets:
    accessKeyId: test
    secretAccessKey: test
---
apiVersion: data.infoblox.com/v1alpha1
kind: Store
metadata:
  name: test-bucket
  labels:
    environment: local
spec:
  connector: s3
  connection:
    bucket: dp-test
    endpoint: http://localhost:4566
    region: us-east-1
    pathStyle: true
  secrets:
    accessKeyId: test
    secretAccessKey: test
