package auth
// Package auth provides authentication handling for DP CLI.
package auth

import (
	"encoding/base64"
	"encoding/json"

























































































































































































































































































}	return os.WriteFile(r.configPath, data, 0600)	}		return err	if err := os.MkdirAll(configDir, 0700); err != nil {	configDir := filepath.Dir(r.configPath)	// Ensure directory exists	}		return err	if err != nil {	data, err := json.MarshalIndent(r.config, "", "  ")func (r *RegistryAuth) saveConfig() error {// saveConfig saves the docker config to disk.}	return r.saveConfig()	delete(r.config.Auths, "https://"+registry)	delete(r.config.Auths, registry)	}		return nil	if r.config == nil || r.config.Auths == nil {func (r *RegistryAuth) Logout(registry string) error {// Logout removes credentials for a registry.}	return r.saveConfig()	// Write config	}		Auth: auth,	r.config.Auths[registry] = AuthEntry{	auth := base64.StdEncoding.EncodeToString([]byte(username + ":" + password))	// Encode credentials	}		}			Auths: make(map[string]AuthEntry),		r.config = &DockerConfig{	if r.config == nil {func (r *RegistryAuth) Login(registry, username, password string) error {// Login stores credentials for a registry.}	return &config, nil	}		return nil, err	if err := json.Unmarshal(data, &config); err != nil {	var config DockerConfig	}		return nil, err	if err != nil {	data, err := os.ReadFile(path)func loadDockerConfig(path string) (*DockerConfig, error) {// loadDockerConfig loads and parses docker config.json.}	return filepath.Join(home, ".docker", "config.json")	}		return ""	if err != nil {	home, err := os.UserHomeDir()	// Default to ~/.docker/config.json	}		}			return path		if _, err := os.Stat(path); err == nil {		path := filepath.Join(xdgConfig, "containers", "auth.json")	if xdgConfig := os.Getenv("XDG_CONFIG_HOME"); xdgConfig != "" {	// Check XDG config	}		return filepath.Join(configDir, "config.json")	if configDir := os.Getenv("DOCKER_CONFIG"); configDir != "" {	// Check DOCKER_CONFIG environment variablefunc getDockerConfigPath() string {// getDockerConfigPath returns the path to docker config.json.}	return nil	}		}			}				return creds				creds.Password = parts[1]				creds.Username = parts[0]			if len(parts) == 2 {			parts := strings.SplitN(string(decoded), ":", 2)		if err == nil {		decoded, err := base64.StdEncoding.DecodeString(entry.Auth)	if entry.Auth != "" {	// Parse auth field (base64 encoded username:password)	}		return creds		creds.Password = entry.Password		creds.Username = entry.Username	if entry.Username != "" {	// Check for username/password	}		return creds		creds.Token = entry.RegistryToken	if entry.RegistryToken != "" {	}		return creds		creds.Token = entry.IdentityToken	if entry.IdentityToken != "" {	// Check for token-based auth	creds := &Credentials{}func (r *RegistryAuth) parseAuthEntry(entry AuthEntry) *Credentials {// parseAuthEntry parses a docker config auth entry.}	return nil	}		}			return r.parseAuthEntry(entry)		if strings.Contains(key, registry) {	for key, entry := range r.config.Auths {	// Try to match partial hostname	}		return r.parseAuthEntry(entry)	if entry, ok := r.config.Auths["https://"+registry+"/v2/"]; ok {	// Try with https:// and /v2/	}		return r.parseAuthEntry(entry)	if entry, ok := r.config.Auths["https://"+registry]; ok {	// Try with https://	}		return r.parseAuthEntry(entry)	if entry, ok := r.config.Auths[registry]; ok {	// Look for exact match first	}		return nil	if r.config == nil || r.config.Auths == nil {func (r *RegistryAuth) getCredentialsFromConfig(registry string) *Credentials {// getCredentialsFromConfig gets credentials from docker config.}	return nil	}		// For now, rely on docker config		// ECR uses AWS credentials - would need AWS SDK	case strings.Contains(registry, "ecr.aws") || strings.Contains(registry, "amazonaws.com"):		}			}				}					Password: string(data),					Username: "_json_key",				return &Credentials{			if err == nil {			data, err := os.ReadFile(token)			// Read service account JSON		if token := os.Getenv("GOOGLE_APPLICATION_CREDENTIALS"); token != "" {	case strings.Contains(registry, "gcr.io") || strings.Contains(registry, "pkg.dev"):		}			}				Password: os.Getenv("DOCKER_PASSWORD"),				Username: username,			return &Credentials{		if username := os.Getenv("DOCKER_USERNAME"); username != "" {	case strings.Contains(registry, "docker.io") || strings.Contains(registry, "hub.docker.com"):		}			}				Token:    token,				Username: "oauth2",			return &Credentials{		if token := os.Getenv("GITHUB_TOKEN"); token != "" {	case strings.Contains(registry, "ghcr.io"):	switch {	// Check for well-known registry environment variables	}		}			Token:    token,			Password: password,			Username: username,		return &Credentials{	if username != "" || token != "" {	token := os.Getenv(envPrefix + "_TOKEN")	password := os.Getenv(envPrefix + "_PASSWORD")	username := os.Getenv(envPrefix + "_USERNAME")	// Try generic first	envPrefix := "DP_REGISTRY"	// or generic: DP_REGISTRY_USERNAME	// Format: DP_REGISTRY_<HOSTNAME>_USERNAME	// Check for registry-specific environment variablesfunc (r *RegistryAuth) getCredentialsFromEnv(registry string) *Credentials {// getCredentialsFromEnv gets credentials from environment variables.}	return nil, nil // No credentials found	}		}			return creds, nil		if creds := r.getCredentialsFromConfig(registry); creds != nil {	if r.config != nil {	// Then check docker config	}		return creds, nil	if creds := r.getCredentialsFromEnv(registry); creds != nil {	// First, check environment variablesfunc (r *RegistryAuth) GetCredentials(registry string) (*Credentials, error) {// GetCredentials retrieves credentials for a registry.}	return auth, nil	}		auth.config = config		}			return nil, fmt.Errorf("failed to load docker config: %w", err)		if err != nil {		config, err := loadDockerConfig(configPath)	if _, err := os.Stat(configPath); err == nil {	}		configPath: configPath,	auth := &RegistryAuth{	configPath := getDockerConfigPath()func NewRegistryAuth() (*RegistryAuth, error) {// NewRegistryAuth creates a new registry auth handler.}	configPath string	config     *DockerConfigtype RegistryAuth struct {// RegistryAuth provides authentication for OCI registries.}	Token    string	Password string	Username stringtype Credentials struct {// Credentials represents parsed registry credentials.}	RegistryToken string `json:"registrytoken,omitempty"`	IdentityToken string `json:"identitytoken,omitempty"`	ServerAddress string `json:"serveraddress,omitempty"`	Email         string `json:"email,omitempty"`	Password      string `json:"password,omitempty"`	Username      string `json:"username,omitempty"`	Auth          string `json:"auth,omitempty"`type AuthEntry struct {// AuthEntry represents an auth entry in Docker config.}	CredHelpers map[string]string    `json:"credHelpers,omitempty"`	Auths       map[string]AuthEntry `json:"auths,omitempty"`type DockerConfig struct {// DockerConfig represents the Docker config.json structure.)	"strings"	"path/filepath"	"os"	"fmt"