apiVersion: datakit.infoblox.dev/v1alpha1
kind: Transform
metadata:
  name: quickstart-demo
  namespace: default
  version: 0.1.0
  labels:
    team: my-team
spec:
  runtime: generic-go
  mode: batch
  image: "${REGISTRY}/quickstart-demo:${VERSION}"

  inputs:
    - asset: quickstart-demo-input

  outputs:
    - asset: quickstart-demo-output

  resources:
    cpu: "1"
    memory: "2Gi"
