apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: marquez
    component: api
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.api.port }}
      targetPort: http
      protocol: TCP
    - name: admin
      port: {{ .Values.api.adminPort }}
      targetPort: admin
      protocol: TCP
  selector:
    app: marquez
    component: api
