package contracts

// ---------------------------------------------------------------------------
// Lock file — pins resolved schema versions for reproducible builds.
// ---------------------------------------------------------------------------

// LockFile represents the dk.lock file that pins resolved schema versions.
// It is generated by `dk lock` and consumed by `dk lint` and `dk run`.
type LockFile struct {
	// Version is the lock file format version.
	Version string `json:"version" yaml:"version"`

	// Schemas lists all resolved schema dependencies.
	Schemas []LockedSchema `json:"schemas,omitempty" yaml:"schemas,omitempty"`
}

// LockedSchema represents a single pinned schema dependency in dk.lock.
type LockedSchema struct {
	// Module is the APX module identifier (e.g., "users", "orders").
	Module string `json:"module" yaml:"module"`

	// Version is the resolved semantic version (e.g., "1.2.3").
	Version string `json:"version" yaml:"version"`

	// Repo is the canonical repository URL where the schema lives.
	Repo string `json:"repo" yaml:"repo"`

	// Ref is the git reference (tag or SHA) for reproducibility.
	Ref string `json:"ref" yaml:"ref"`

	// Format is the schema format (e.g., "parquet", "avro", "json", "protobuf").
	Format string `json:"format" yaml:"format"`

	// Checksum is the integrity hash of the schema content.
	Checksum string `json:"checksum" yaml:"checksum"`
}
