# LocalStack values for dk local development
replicaCount: 1

image:
  repository: localstack/localstack
  pullPolicy: IfNotPresent
  tag: "3.8.1"

service:
  type: ClusterIP
  port: 4566

# AWS services to enable
services: "s3"

resources:
  limits:
    cpu: "1"
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 256Mi

persistence:
  enabled: false
