apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: redpanda-console
    app.kubernetes.io/name: redpanda-console
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: redpanda-console
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: redpanda-console
        app.kubernetes.io/name: redpanda-console
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: redpanda-console
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: KAFKA_BROKERS
              value: "{{ .Values.kafka.brokers }}"
            - name: KAFKA_SCHEMAREGISTRY_ENABLED
              value: "{{ .Values.schemaRegistry.enabled }}"
            - name: KAFKA_SCHEMAREGISTRY_URLS
              value: "{{ .Values.schemaRegistry.urls }}"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /admin/health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /admin/health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
