FROM golang:1.21-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o /destination .

FROM alpine:3.19
COPY --from=builder /destination /destination
ENTRYPOINT ["/destination"]
